
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Data.EntityClient
Imports System.ComponentModel
Imports System.Xml.Serialization
Imports System.Runtime.Serialization

<Assembly: EdmSchemaAttribute("5e0f34dd-4a93-48e7-aa13-f3223128c211")>

#Region "Contexts"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
Public Partial Class Student2Container
    Inherits ObjectContext

    #Region "Constructors"

    ''' <summary>
    ''' Initializes a new Student2Container object using the connection string found in the 'Student2Container' section of the application configuration file.
    ''' </summary>
    Public Sub New()
        MyBase.New("name=Student2Container", "Student2Container")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new Student2Container object.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "Student2Container")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new Student2Container object.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "Student2Container")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    #End Region

    #Region "Partial Methods"

    Partial Private Sub OnContextCreated()
    End Sub

    #End Region

    #Region "ObjectSet Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Student2_UNNEST() As ObjectSet(Of Student2_UNNEST)
        Get
            If (_Student2_UNNEST Is Nothing) Then
                _Student2_UNNEST = MyBase.CreateObjectSet(Of Student2_UNNEST)("Student2_UNNEST")
            End If
            Return _Student2_UNNEST
        End Get
    End Property

    Private _Student2_UNNEST As ObjectSet(Of Student2_UNNEST)

    #End Region
    #Region "AddTo Methods"

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Student2_UNNEST EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToStudent2_UNNEST(ByVal student2_UNNEST As Student2_UNNEST)
        MyBase.AddObject("Student2_UNNEST", student2_UNNEST)
    End Sub

    #End Region
End Class

#End Region
#Region "Entities"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="Student2", Name:="Student2_UNNEST")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Student2_UNNEST
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Student2_UNNEST object.
    ''' </summary>
    ''' <param name="id">Initial value of the ID property.</param>
    Public Shared Function CreateStudent2_UNNEST(id As Global.System.String) As Student2_UNNEST
        Dim student2_UNNEST as Student2_UNNEST = New Student2_UNNEST
        student2_UNNEST.ID = id
        Return student2_UNNEST
    End Function

    #End Region
    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ID() As Global.System.String
        Get
            Return _ID
        End Get
        Set
            If (_ID <> Value) Then
                OnIDChanging(value)
                ReportPropertyChanging("ID")
                _ID = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("ID")
                OnIDChanged()
            End If
        End Set
    End Property

    Private _ID As Global.System.String
    Private Partial Sub OnIDChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property FNAME() As Global.System.String
        Get
            Return _FNAME
        End Get
        Set
            OnFNAMEChanging(value)
            ReportPropertyChanging("FNAME")
            _FNAME = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("FNAME")
            OnFNAMEChanged()
        End Set
    End Property

    Private _FNAME As Global.System.String
    Private Partial Sub OnFNAMEChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnFNAMEChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property LNAME() As Global.System.String
        Get
            Return _LNAME
        End Get
        Set
            OnLNAMEChanging(value)
            ReportPropertyChanging("LNAME")
            _LNAME = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("LNAME")
            OnLNAMEChanged()
        End Set
    End Property

    Private _LNAME As Global.System.String
    Private Partial Sub OnLNAMEChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnLNAMEChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property MAJOR() As Global.System.String
        Get
            Return _MAJOR
        End Get
        Set
            OnMAJORChanging(value)
            ReportPropertyChanging("MAJOR")
            _MAJOR = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("MAJOR")
            OnMAJORChanged()
        End Set
    End Property

    Private _MAJOR As Global.System.String
    Private Partial Sub OnMAJORChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnMAJORChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property MINOR() As Global.System.String
        Get
            Return _MINOR
        End Get
        Set
            OnMINORChanging(value)
            ReportPropertyChanging("MINOR")
            _MINOR = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("MINOR")
            OnMINORChanged()
        End Set
    End Property

    Private _MINOR As Global.System.String
    Private Partial Sub OnMINORChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnMINORChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property SEMESTER() As Global.System.String
        Get
            Return _SEMESTER
        End Get
        Set
            OnSEMESTERChanging(value)
            ReportPropertyChanging("SEMESTER")
            _SEMESTER = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("SEMESTER")
            OnSEMESTERChanged()
        End Set
    End Property

    Private _SEMESTER As Global.System.String
    Private Partial Sub OnSEMESTERChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnSEMESTERChanged()
    End Sub

    #End Region
End Class

#End Region

