//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_CGA_MV_SUB
    {
        public STUDENT_CGA_MV_SUB()
        {
            this.STUDENT_CGA_MS_SUB = new HashSet<STUDENT_CGA_MS_SUB>();
        }
    
        public string ID { get; set; }
        public int CGA_MV_KEY { get; set; }
        public string SEMESTER { get; set; }
    
        public virtual ICollection<STUDENT_CGA_MS_SUB> STUDENT_CGA_MS_SUB { get; set; }
        public virtual STUDENT_NF_SUB STUDENT_NF_SUB { get; set; }
    }
}
