//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_NF_SUB
    {
        public STUDENT_NF_SUB()
        {
            this.STUDENT_CGA_MV_SUB = new HashSet<STUDENT_CGA_MV_SUB>();
        }
    
        public string ID { get; set; }
        public string LNAME { get; set; }
        public string FNAME { get; set; }
        public string MAJOR { get; set; }
        public string MINOR { get; set; }
        public string ADVISOR { get; set; }
        public Nullable<double> GPA1 { get; set; }
    
        public virtual ICollection<STUDENT_CGA_MV_SUB> STUDENT_CGA_MV_SUB { get; set; }
    }
}
