'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Student
    Public Property ID As String
    Public Property LNAME As String
    Public Property FNAME As String
    Public Property MAJOR As String
    Public Property MINOR As String
    Public Property ADVISOR As String
    Public Property GPA1 As String

    Public Overridable Property Semesters As ICollection(Of Semester) = New HashSet(Of Semester)

End Class
