//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER
    {
        public CUSTOMER()
        {
            this.CUSTOMER_ORDERS = new HashSet<CUSTOMER_ORDERS>();
        }
    
        public int CUSTID { get; set; }
        public string SAL { get; set; }
        public string FNAME { get; set; }
        public string LNAME { get; set; }
        public string FULLNAME { get; set; }
        public string COMPANY { get; set; }
        public string ADDR1 { get; set; }
        public string ADDR2 { get; set; }
        public string FULLADDR { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string STATENAME { get; set; }
        public string ZIP { get; set; }
        public string PHONE { get; set; }
    
        public virtual ICollection<CUSTOMER_ORDERS> CUSTOMER_ORDERS { get; set; }
    }
}
