
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Data.EntityClient
Imports System.ComponentModel
Imports System.Xml.Serialization
Imports System.Runtime.Serialization

<Assembly: EdmSchemaAttribute("9eef26bd-06cd-4682-bd23-f0630f3a3655")>

#Region "Contexts"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
Public Partial Class CustomerContainer
    Inherits ObjectContext

    #Region "Constructors"

    ''' <summary>
    ''' Initializes a new CustomerContainer object using the connection string found in the 'CustomerContainer' section of the application configuration file.
    ''' </summary>
    Public Sub New()
        MyBase.New("name=CustomerContainer", "CustomerContainer")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new CustomerContainer object.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "CustomerContainer")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new CustomerContainer object.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "CustomerContainer")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    #End Region

    #Region "Partial Methods"

    Partial Private Sub OnContextCreated()
    End Sub

    #End Region

    #Region "ObjectSet Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property CUSTOMERS() As ObjectSet(Of CUSTOMER)
        Get
            If (_CUSTOMERS Is Nothing) Then
                _CUSTOMERS = MyBase.CreateObjectSet(Of CUSTOMER)("CUSTOMERS")
            End If
            Return _CUSTOMERS
        End Get
    End Property

    Private _CUSTOMERS As ObjectSet(Of CUSTOMER)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property CUSTOMERS_MV() As ObjectSet(Of CUSTOMER_MV)
        Get
            If (_CUSTOMERS_MV Is Nothing) Then
                _CUSTOMERS_MV = MyBase.CreateObjectSet(Of CUSTOMER_MV)("CUSTOMERS_MV")
            End If
            Return _CUSTOMERS_MV
        End Get
    End Property

    Private _CUSTOMERS_MV As ObjectSet(Of CUSTOMER_MV)

    #End Region
    #Region "AddTo Methods"

    ''' <summary>
    ''' Deprecated Method for adding a new object to the CUSTOMERS EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToCUSTOMERS(ByVal cUSTOMER As CUSTOMER)
        MyBase.AddObject("CUSTOMERS", cUSTOMER)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the CUSTOMERS_MV EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToCUSTOMERS_MV(ByVal cUSTOMER_MV As CUSTOMER_MV)
        MyBase.AddObject("CUSTOMERS_MV", cUSTOMER_MV)
    End Sub

    #End Region
End Class

#End Region
#Region "Entities"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="Customer", Name:="CUSTOMER")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class CUSTOMER
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new CUSTOMER object.
    ''' </summary>
    ''' <param name="cUSTID">Initial value of the CUSTID property.</param>
    Public Shared Function CreateCUSTOMER(cUSTID As Global.System.Int32) As CUSTOMER
        Dim cUSTOMER as CUSTOMER = New CUSTOMER
        cUSTOMER.CUSTID = cUSTID
        Return cUSTOMER
    End Function

    #End Region
    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property CUSTID() As Global.System.Int32
        Get
            Return _CUSTID
        End Get
        Set
            If (_CUSTID <> Value) Then
                OnCUSTIDChanging(value)
                ReportPropertyChanging("CUSTID")
                _CUSTID = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("CUSTID")
                OnCUSTIDChanged()
            End If
        End Set
    End Property

    Private _CUSTID As Global.System.Int32
    Private Partial Sub OnCUSTIDChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnCUSTIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property PHONE() As Global.System.String
        Get
            Return _PHONE
        End Get
        Set
            OnPHONEChanging(value)
            ReportPropertyChanging("PHONE")
            _PHONE = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("PHONE")
            OnPHONEChanged()
        End Set
    End Property

    Private _PHONE As Global.System.String
    Private Partial Sub OnPHONEChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnPHONEChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property ZIP() As Global.System.String
        Get
            Return _ZIP
        End Get
        Set
            OnZIPChanging(value)
            ReportPropertyChanging("ZIP")
            _ZIP = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("ZIP")
            OnZIPChanged()
        End Set
    End Property

    Private _ZIP As Global.System.String
    Private Partial Sub OnZIPChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnZIPChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property STATENAME() As Global.System.String
        Get
            Return _STATENAME
        End Get
        Set
            OnSTATENAMEChanging(value)
            ReportPropertyChanging("STATENAME")
            _STATENAME = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("STATENAME")
            OnSTATENAMEChanged()
        End Set
    End Property

    Private _STATENAME As Global.System.String
    Private Partial Sub OnSTATENAMEChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnSTATENAMEChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property STATE() As Global.System.String
        Get
            Return _STATE
        End Get
        Set
            OnSTATEChanging(value)
            ReportPropertyChanging("STATE")
            _STATE = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("STATE")
            OnSTATEChanged()
        End Set
    End Property

    Private _STATE As Global.System.String
    Private Partial Sub OnSTATEChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnSTATEChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property CITY() As Global.System.String
        Get
            Return _CITY
        End Get
        Set
            OnCITYChanging(value)
            ReportPropertyChanging("CITY")
            _CITY = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("CITY")
            OnCITYChanged()
        End Set
    End Property

    Private _CITY As Global.System.String
    Private Partial Sub OnCITYChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnCITYChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property FULLADDR() As Global.System.String
        Get
            Return _FULLADDR
        End Get
        Set
            OnFULLADDRChanging(value)
            ReportPropertyChanging("FULLADDR")
            _FULLADDR = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("FULLADDR")
            OnFULLADDRChanged()
        End Set
    End Property

    Private _FULLADDR As Global.System.String
    Private Partial Sub OnFULLADDRChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnFULLADDRChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property ADDR2() As Global.System.String
        Get
            Return _ADDR2
        End Get
        Set
            OnADDR2Changing(value)
            ReportPropertyChanging("ADDR2")
            _ADDR2 = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("ADDR2")
            OnADDR2Changed()
        End Set
    End Property

    Private _ADDR2 As Global.System.String
    Private Partial Sub OnADDR2Changing(value As Global.System.String)
    End Sub

    Private Partial Sub OnADDR2Changed()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property ADDR1() As Global.System.String
        Get
            Return _ADDR1
        End Get
        Set
            OnADDR1Changing(value)
            ReportPropertyChanging("ADDR1")
            _ADDR1 = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("ADDR1")
            OnADDR1Changed()
        End Set
    End Property

    Private _ADDR1 As Global.System.String
    Private Partial Sub OnADDR1Changing(value As Global.System.String)
    End Sub

    Private Partial Sub OnADDR1Changed()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property COMPANY() As Global.System.String
        Get
            Return _COMPANY
        End Get
        Set
            OnCOMPANYChanging(value)
            ReportPropertyChanging("COMPANY")
            _COMPANY = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("COMPANY")
            OnCOMPANYChanged()
        End Set
    End Property

    Private _COMPANY As Global.System.String
    Private Partial Sub OnCOMPANYChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnCOMPANYChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property FULLNAME() As Global.System.String
        Get
            Return _FULLNAME
        End Get
        Set
            OnFULLNAMEChanging(value)
            ReportPropertyChanging("FULLNAME")
            _FULLNAME = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("FULLNAME")
            OnFULLNAMEChanged()
        End Set
    End Property

    Private _FULLNAME As Global.System.String
    Private Partial Sub OnFULLNAMEChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnFULLNAMEChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property LNAME() As Global.System.String
        Get
            Return _LNAME
        End Get
        Set
            OnLNAMEChanging(value)
            ReportPropertyChanging("LNAME")
            _LNAME = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("LNAME")
            OnLNAMEChanged()
        End Set
    End Property

    Private _LNAME As Global.System.String
    Private Partial Sub OnLNAMEChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnLNAMEChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property FNAME() As Global.System.String
        Get
            Return _FNAME
        End Get
        Set
            OnFNAMEChanging(value)
            ReportPropertyChanging("FNAME")
            _FNAME = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("FNAME")
            OnFNAMEChanged()
        End Set
    End Property

    Private _FNAME As Global.System.String
    Private Partial Sub OnFNAMEChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnFNAMEChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property SAL() As Global.System.String
        Get
            Return _SAL
        End Get
        Set
            OnSALChanging(value)
            ReportPropertyChanging("SAL")
            _SAL = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("SAL")
            OnSALChanged()
        End Set
    End Property

    Private _SAL As Global.System.String
    Private Partial Sub OnSALChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnSALChanged()
    End Sub

    #End Region
End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="Customer", Name:="CUSTOMER_MV")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class CUSTOMER_MV
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new CUSTOMER_MV object.
    ''' </summary>
    ''' <param name="cUSTID">Initial value of the CUSTID property.</param>
    ''' <param name="fNAME">Initial value of the FNAME property.</param>
    ''' <param name="lNAME">Initial value of the LNAME property.</param>
    Public Shared Function CreateCUSTOMER_MV(cUSTID As Global.System.Int32, fNAME As Global.System.String, lNAME As Global.System.String) As CUSTOMER_MV
        Dim cUSTOMER_MV as CUSTOMER_MV = New CUSTOMER_MV
        cUSTOMER_MV.CUSTID = cUSTID
        cUSTOMER_MV.FNAME = fNAME
        cUSTOMER_MV.LNAME = lNAME
        Return cUSTOMER_MV
    End Function

    #End Region
    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property CUSTID() As Global.System.Int32
        Get
            Return _CUSTID
        End Get
        Set
            If (_CUSTID <> Value) Then
                OnCUSTIDChanging(value)
                ReportPropertyChanging("CUSTID")
                _CUSTID = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("CUSTID")
                OnCUSTIDChanged()
            End If
        End Set
    End Property

    Private _CUSTID As Global.System.Int32
    Private Partial Sub OnCUSTIDChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnCUSTIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property FNAME() As Global.System.String
        Get
            Return _FNAME
        End Get
        Set
            OnFNAMEChanging(value)
            ReportPropertyChanging("FNAME")
            _FNAME = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("FNAME")
            OnFNAMEChanged()
        End Set
    End Property

    Private _FNAME As Global.System.String
    Private Partial Sub OnFNAMEChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnFNAMEChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property LNAME() As Global.System.String
        Get
            Return _LNAME
        End Get
        Set
            OnLNAMEChanging(value)
            ReportPropertyChanging("LNAME")
            _LNAME = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("LNAME")
            OnLNAMEChanged()
        End Set
    End Property

    Private _LNAME As Global.System.String
    Private Partial Sub OnLNAMEChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnLNAMEChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property SVC_PAID_DATE() As Nullable(Of Global.System.DateTime)
        Get
            Return _SVC_PAID_DATE
        End Get
        Set
            OnSVC_PAID_DATEChanging(value)
            ReportPropertyChanging("SVC_PAID_DATE")
            _SVC_PAID_DATE = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("SVC_PAID_DATE")
            OnSVC_PAID_DATEChanged()
        End Set
    End Property

    Private _SVC_PAID_DATE As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnSVC_PAID_DATEChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnSVC_PAID_DATEChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property SVC_PRICE() As Nullable(Of Global.System.Int32)
        Get
            Return _SVC_PRICE
        End Get
        Set
            OnSVC_PRICEChanging(value)
            ReportPropertyChanging("SVC_PRICE")
            _SVC_PRICE = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("SVC_PRICE")
            OnSVC_PRICEChanged()
        End Set
    End Property

    Private _SVC_PRICE As Nullable(Of Global.System.Int32)
    Private Partial Sub OnSVC_PRICEChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnSVC_PRICEChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property SVC_END() As Nullable(Of Global.System.DateTime)
        Get
            Return _SVC_END
        End Get
        Set
            OnSVC_ENDChanging(value)
            ReportPropertyChanging("SVC_END")
            _SVC_END = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("SVC_END")
            OnSVC_ENDChanged()
        End Set
    End Property

    Private _SVC_END As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnSVC_ENDChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnSVC_ENDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property SVC_START() As Nullable(Of Global.System.DateTime)
        Get
            Return _SVC_START
        End Get
        Set
            OnSVC_STARTChanging(value)
            ReportPropertyChanging("SVC_START")
            _SVC_START = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("SVC_START")
            OnSVC_STARTChanged()
        End Set
    End Property

    Private _SVC_START As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnSVC_STARTChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnSVC_STARTChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property DISCOUNT() As Nullable(Of Global.System.Decimal)
        Get
            Return _DISCOUNT
        End Get
        Set
            OnDISCOUNTChanging(value)
            ReportPropertyChanging("DISCOUNT")
            _DISCOUNT = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("DISCOUNT")
            OnDISCOUNTChanged()
        End Set
    End Property

    Private _DISCOUNT As Nullable(Of Global.System.Decimal)
    Private Partial Sub OnDISCOUNTChanging(value As Nullable(Of Global.System.Decimal))
    End Sub

    Private Partial Sub OnDISCOUNTChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property PRICE() As Nullable(Of Global.System.Int32)
        Get
            Return _PRICE
        End Get
        Set
            OnPRICEChanging(value)
            ReportPropertyChanging("PRICE")
            _PRICE = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("PRICE")
            OnPRICEChanged()
        End Set
    End Property

    Private _PRICE As Nullable(Of Global.System.Int32)
    Private Partial Sub OnPRICEChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnPRICEChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property LIST_PRICE() As Nullable(Of Global.System.Int32)
        Get
            Return _LIST_PRICE
        End Get
        Set
            OnLIST_PRICEChanging(value)
            ReportPropertyChanging("LIST_PRICE")
            _LIST_PRICE = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("LIST_PRICE")
            OnLIST_PRICEChanged()
        End Set
    End Property

    Private _LIST_PRICE As Nullable(Of Global.System.Int32)
    Private Partial Sub OnLIST_PRICEChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnLIST_PRICEChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property PAID_DATE() As Nullable(Of Global.System.DateTime)
        Get
            Return _PAID_DATE
        End Get
        Set
            OnPAID_DATEChanging(value)
            ReportPropertyChanging("PAID_DATE")
            _PAID_DATE = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("PAID_DATE")
            OnPAID_DATEChanged()
        End Set
    End Property

    Private _PAID_DATE As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnPAID_DATEChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnPAID_DATEChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property BUY_DATE() As Nullable(Of Global.System.DateTime)
        Get
            Return _BUY_DATE
        End Get
        Set
            OnBUY_DATEChanging(value)
            ReportPropertyChanging("BUY_DATE")
            _BUY_DATE = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("BUY_DATE")
            OnBUY_DATEChanged()
        End Set
    End Property

    Private _BUY_DATE As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnBUY_DATEChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnBUY_DATEChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property SER_NUM() As Global.System.String
        Get
            Return _SER_NUM
        End Get
        Set
            OnSER_NUMChanging(value)
            ReportPropertyChanging("SER_NUM")
            _SER_NUM = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("SER_NUM")
            OnSER_NUMChanged()
        End Set
    End Property

    Private _SER_NUM As Global.System.String
    Private Partial Sub OnSER_NUMChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnSER_NUMChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property DESCRIPTION() As Global.System.String
        Get
            Return _DESCRIPTION
        End Get
        Set
            OnDESCRIPTIONChanging(value)
            ReportPropertyChanging("DESCRIPTION")
            _DESCRIPTION = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("DESCRIPTION")
            OnDESCRIPTIONChanged()
        End Set
    End Property

    Private _DESCRIPTION As Global.System.String
    Private Partial Sub OnDESCRIPTIONChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnDESCRIPTIONChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property PRODID() As Global.System.String
        Get
            Return _PRODID
        End Get
        Set
            OnPRODIDChanging(value)
            ReportPropertyChanging("PRODID")
            _PRODID = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("PRODID")
            OnPRODIDChanged()
        End Set
    End Property

    Private _PRODID As Global.System.String
    Private Partial Sub OnPRODIDChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnPRODIDChanged()
    End Sub

    #End Region
End Class

#End Region

