//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace EntityFramework_ExecuteStoreQuery_UNNEST
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Student2Container : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Student2Container object using the connection string found in the 'Student2Container' section of the application configuration file.
        /// </summary>
        public Student2Container() : base("name=Student2Container", "Student2Container")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Student2Container object.
        /// </summary>
        public Student2Container(string connectionString) : base(connectionString, "Student2Container")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Student2Container object.
        /// </summary>
        public Student2Container(EntityConnection connection) : base(connection, "Student2Container")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Student2_UNNEST> Student2_UNNEST
        {
            get
            {
                if ((_Student2_UNNEST == null))
                {
                    _Student2_UNNEST = base.CreateObjectSet<Student2_UNNEST>("Student2_UNNEST");
                }
                return _Student2_UNNEST;
            }
        }
        private ObjectSet<Student2_UNNEST> _Student2_UNNEST;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Student2_UNNEST EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToStudent2_UNNEST(Student2_UNNEST student2_UNNEST)
        {
            base.AddObject("Student2_UNNEST", student2_UNNEST);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Student2", Name="Student2_UNNEST")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Student2_UNNEST : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Student2_UNNEST object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static Student2_UNNEST CreateStudent2_UNNEST(global::System.String id)
        {
            Student2_UNNEST student2_UNNEST = new Student2_UNNEST();
            student2_UNNEST.ID = id;
            return student2_UNNEST;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.String _ID;
        partial void OnIDChanging(global::System.String value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FNAME
        {
            get
            {
                return _FNAME;
            }
            set
            {
                OnFNAMEChanging(value);
                ReportPropertyChanging("FNAME");
                _FNAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FNAME");
                OnFNAMEChanged();
            }
        }
        private global::System.String _FNAME;
        partial void OnFNAMEChanging(global::System.String value);
        partial void OnFNAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LNAME
        {
            get
            {
                return _LNAME;
            }
            set
            {
                OnLNAMEChanging(value);
                ReportPropertyChanging("LNAME");
                _LNAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LNAME");
                OnLNAMEChanged();
            }
        }
        private global::System.String _LNAME;
        partial void OnLNAMEChanging(global::System.String value);
        partial void OnLNAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MAJOR
        {
            get
            {
                return _MAJOR;
            }
            set
            {
                OnMAJORChanging(value);
                ReportPropertyChanging("MAJOR");
                _MAJOR = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MAJOR");
                OnMAJORChanged();
            }
        }
        private global::System.String _MAJOR;
        partial void OnMAJORChanging(global::System.String value);
        partial void OnMAJORChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MINOR
        {
            get
            {
                return _MINOR;
            }
            set
            {
                OnMINORChanging(value);
                ReportPropertyChanging("MINOR");
                _MINOR = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MINOR");
                OnMINORChanged();
            }
        }
        private global::System.String _MINOR;
        partial void OnMINORChanging(global::System.String value);
        partial void OnMINORChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SEMESTER
        {
            get
            {
                return _SEMESTER;
            }
            set
            {
                OnSEMESTERChanging(value);
                ReportPropertyChanging("SEMESTER");
                _SEMESTER = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SEMESTER");
                OnSEMESTERChanged();
            }
        }
        private global::System.String _SEMESTER;
        partial void OnSEMESTERChanging(global::System.String value);
        partial void OnSEMESTERChanged();

        #endregion
    
    }

    #endregion
    
}
