
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Data.EntityClient
Imports System.ComponentModel
Imports System.Xml.Serialization
Imports System.Runtime.Serialization

<Assembly: EdmSchemaAttribute("a014b6d3-db08-41d1-be85-67993dcb4ebb")>
#Region "EDM Relationship Metadata"
<Assembly: EdmRelationshipAttribute("Student", "StudentSemester", "Student", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Student), "Semester", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Semester), True)>
<Assembly: EdmRelationshipAttribute("Student", "SemesterCourse", "Semester", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Semester), "Course", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Course), True)>

#End Region

#Region "Contexts"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
Public Partial Class StudentContainer
    Inherits ObjectContext

    #Region "Constructors"

    ''' <summary>
    ''' Initializes a new StudentContainer object using the connection string found in the 'StudentContainer' section of the application configuration file.
    ''' </summary>
    Public Sub New()
        MyBase.New("name=StudentContainer", "StudentContainer")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new StudentContainer object.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "StudentContainer")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new StudentContainer object.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "StudentContainer")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    #End Region

    #Region "Partial Methods"

    Partial Private Sub OnContextCreated()
    End Sub

    #End Region

    #Region "ObjectSet Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Students() As ObjectSet(Of Student)
        Get
            If (_Students Is Nothing) Then
                _Students = MyBase.CreateObjectSet(Of Student)("Students")
            End If
            Return _Students
        End Get
    End Property

    Private _Students As ObjectSet(Of Student)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Semesters() As ObjectSet(Of Semester)
        Get
            If (_Semesters Is Nothing) Then
                _Semesters = MyBase.CreateObjectSet(Of Semester)("Semesters")
            End If
            Return _Semesters
        End Get
    End Property

    Private _Semesters As ObjectSet(Of Semester)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Courses() As ObjectSet(Of Course)
        Get
            If (_Courses Is Nothing) Then
                _Courses = MyBase.CreateObjectSet(Of Course)("Courses")
            End If
            Return _Courses
        End Get
    End Property

    Private _Courses As ObjectSet(Of Course)

    #End Region
    #Region "AddTo Methods"

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Students EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToStudents(ByVal student As Student)
        MyBase.AddObject("Students", student)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Semesters EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToSemesters(ByVal semester As Semester)
        MyBase.AddObject("Semesters", semester)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Courses EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToCourses(ByVal course As Course)
        MyBase.AddObject("Courses", course)
    End Sub

    #End Region
    #Region "Function Imports"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    ''' <param name="cMD">No Metadata Documentation available.</param>
    ''' <param name="oPTIONS">No Metadata Documentation available.</param>
    ''' <param name="rESULT">No Metadata Documentation available.</param>
    ''' <param name="xSD_DATA">No Metadata Documentation available.</param>
    ''' <param name="eRRMSG">No Metadata Documentation available.</param>
    ''' <param name="eRRNUM">No Metadata Documentation available.</param>
    Public Function GetXmlSubroutine(cMD As Global.System.String, oPTIONS As Global.System.String, rESULT As ObjectParameter, xSD_DATA As ObjectParameter, eRRMSG As ObjectParameter, eRRNUM As ObjectParameter) As Integer
        Dim cMDParameter As ObjectParameter
        If (cMD IsNot Nothing)
            cMDParameter = New ObjectParameter("CMD", cMD)
        Else
            cMDParameter = New ObjectParameter("CMD", GetType(Global.System.String))
        End If

        Dim oPTIONSParameter As ObjectParameter
        If (oPTIONS IsNot Nothing)
            oPTIONSParameter = New ObjectParameter("OPTIONS", oPTIONS)
        Else
            oPTIONSParameter = New ObjectParameter("OPTIONS", GetType(Global.System.String))
        End If

        Return MyBase.ExecuteFunction("GetXmlSubroutine", cMDParameter, oPTIONSParameter, rESULT, xSD_DATA, eRRMSG, eRRNUM)

    End Function

    #End Region
End Class

#End Region
#Region "Entities"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="Student", Name:="Course")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Course
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Course object.
    ''' </summary>
    ''' <param name="id">Initial value of the ID property.</param>
    ''' <param name="cGA_MV_KEY">Initial value of the CGA_MV_KEY property.</param>
    ''' <param name="cGA_MS_KEY">Initial value of the CGA_MS_KEY property.</param>
    Public Shared Function CreateCourse(id As Global.System.String, cGA_MV_KEY As Global.System.Int32, cGA_MS_KEY As Global.System.Int32) As Course
        Dim course as Course = New Course
        course.ID = id
        course.CGA_MV_KEY = cGA_MV_KEY
        course.CGA_MS_KEY = cGA_MS_KEY
        Return course
    End Function

    #End Region
    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ID() As Global.System.String
        Get
            Return _ID
        End Get
        Set
            If (_ID <> Value) Then
                OnIDChanging(value)
                ReportPropertyChanging("ID")
                _ID = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("ID")
                OnIDChanged()
            End If
        End Set
    End Property

    Private _ID As Global.System.String
    Private Partial Sub OnIDChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property CGA_MV_KEY() As Global.System.Int32
        Get
            Return _CGA_MV_KEY
        End Get
        Set
            If (_CGA_MV_KEY <> Value) Then
                OnCGA_MV_KEYChanging(value)
                ReportPropertyChanging("CGA_MV_KEY")
                _CGA_MV_KEY = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("CGA_MV_KEY")
                OnCGA_MV_KEYChanged()
            End If
        End Set
    End Property

    Private _CGA_MV_KEY As Global.System.Int32
    Private Partial Sub OnCGA_MV_KEYChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnCGA_MV_KEYChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property CGA_MS_KEY() As Global.System.Int32
        Get
            Return _CGA_MS_KEY
        End Get
        Set
            If (_CGA_MS_KEY <> Value) Then
                OnCGA_MS_KEYChanging(value)
                ReportPropertyChanging("CGA_MS_KEY")
                _CGA_MS_KEY = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("CGA_MS_KEY")
                OnCGA_MS_KEYChanged()
            End If
        End Set
    End Property

    Private _CGA_MS_KEY As Global.System.Int32
    Private Partial Sub OnCGA_MS_KEYChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnCGA_MS_KEYChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property COURSE_NBR() As Global.System.String
        Get
            Return _COURSE_NBR
        End Get
        Set
            OnCOURSE_NBRChanging(value)
            ReportPropertyChanging("COURSE_NBR")
            _COURSE_NBR = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("COURSE_NBR")
            OnCOURSE_NBRChanged()
        End Set
    End Property

    Private _COURSE_NBR As Global.System.String
    Private Partial Sub OnCOURSE_NBRChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnCOURSE_NBRChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property COURSE_HOURS() As Global.System.String
        Get
            Return _COURSE_HOURS
        End Get
        Set
            OnCOURSE_HOURSChanging(value)
            ReportPropertyChanging("COURSE_HOURS")
            _COURSE_HOURS = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("COURSE_HOURS")
            OnCOURSE_HOURSChanged()
        End Set
    End Property

    Private _COURSE_HOURS As Global.System.String
    Private Partial Sub OnCOURSE_HOURSChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnCOURSE_HOURSChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property COURSE_NAME() As Global.System.String
        Get
            Return _COURSE_NAME
        End Get
        Set
            OnCOURSE_NAMEChanging(value)
            ReportPropertyChanging("COURSE_NAME")
            _COURSE_NAME = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("COURSE_NAME")
            OnCOURSE_NAMEChanged()
        End Set
    End Property

    Private _COURSE_NAME As Global.System.String
    Private Partial Sub OnCOURSE_NAMEChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnCOURSE_NAMEChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property TEACHER() As Global.System.String
        Get
            Return _TEACHER
        End Get
        Set
            OnTEACHERChanging(value)
            ReportPropertyChanging("TEACHER")
            _TEACHER = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("TEACHER")
            OnTEACHERChanged()
        End Set
    End Property

    Private _TEACHER As Global.System.String
    Private Partial Sub OnTEACHERChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnTEACHERChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property COURSE_GRD() As Global.System.String
        Get
            Return _COURSE_GRD
        End Get
        Set
            OnCOURSE_GRDChanging(value)
            ReportPropertyChanging("COURSE_GRD")
            _COURSE_GRD = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("COURSE_GRD")
            OnCOURSE_GRDChanged()
        End Set
    End Property

    Private _COURSE_GRD As Global.System.String
    Private Partial Sub OnCOURSE_GRDChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnCOURSE_GRDChanged()
    End Sub

    #End Region
    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("Student", "SemesterCourse", "Semester")>
    Public Property Semester() As Semester
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Semester)("Student.SemesterCourse", "Semester").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Semester)("Student.SemesterCourse", "Semester").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property SemesterReference() As EntityReference(Of Semester)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Semester)("Student.SemesterCourse", "Semester")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Semester)("Student.SemesterCourse", "Semester", value)
            End If
        End Set
    End Property

    #End Region
End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="Student", Name:="Semester")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Semester
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Semester object.
    ''' </summary>
    ''' <param name="id">Initial value of the ID property.</param>
    ''' <param name="cGA_MV_KEY">Initial value of the CGA_MV_KEY property.</param>
    Public Shared Function CreateSemester(id As Global.System.String, cGA_MV_KEY As Global.System.Int32) As Semester
        Dim semester as Semester = New Semester
        semester.ID = id
        semester.CGA_MV_KEY = cGA_MV_KEY
        Return semester
    End Function

    #End Region
    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ID() As Global.System.String
        Get
            Return _ID
        End Get
        Set
            If (_ID <> Value) Then
                OnIDChanging(value)
                ReportPropertyChanging("ID")
                _ID = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("ID")
                OnIDChanged()
            End If
        End Set
    End Property

    Private _ID As Global.System.String
    Private Partial Sub OnIDChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property CGA_MV_KEY() As Global.System.Int32
        Get
            Return _CGA_MV_KEY
        End Get
        Set
            If (_CGA_MV_KEY <> Value) Then
                OnCGA_MV_KEYChanging(value)
                ReportPropertyChanging("CGA_MV_KEY")
                _CGA_MV_KEY = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("CGA_MV_KEY")
                OnCGA_MV_KEYChanged()
            End If
        End Set
    End Property

    Private _CGA_MV_KEY As Global.System.Int32
    Private Partial Sub OnCGA_MV_KEYChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnCGA_MV_KEYChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property SEMESTER() As Global.System.String
        Get
            Return _SEMESTER
        End Get
        Set
            OnSEMESTERChanging(value)
            ReportPropertyChanging("SEMESTER")
            _SEMESTER = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("SEMESTER")
            OnSEMESTERChanged()
        End Set
    End Property

    Private _SEMESTER As Global.System.String
    Private Partial Sub OnSEMESTERChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnSEMESTERChanged()
    End Sub

    #End Region
    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("Student", "StudentSemester", "Student")>
    Public Property Student() As Student
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Student)("Student.StudentSemester", "Student").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Student)("Student.StudentSemester", "Student").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property StudentReference() As EntityReference(Of Student)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Student)("Student.StudentSemester", "Student")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Student)("Student.StudentSemester", "Student", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("Student", "SemesterCourse", "Course")>
     Public Property Courses() As EntityCollection(Of Course)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Course)("Student.SemesterCourse", "Course")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Course)("Student.SemesterCourse", "Course", value)
            End If
        End Set
    End Property

    #End Region
End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="Student", Name:="Student")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Student
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Student object.
    ''' </summary>
    ''' <param name="id">Initial value of the ID property.</param>
    Public Shared Function CreateStudent(id As Global.System.String) As Student
        Dim student as Student = New Student
        student.ID = id
        Return student
    End Function

    #End Region
    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ID() As Global.System.String
        Get
            Return _ID
        End Get
        Set
            If (_ID <> Value) Then
                OnIDChanging(value)
                ReportPropertyChanging("ID")
                _ID = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("ID")
                OnIDChanged()
            End If
        End Set
    End Property

    Private _ID As Global.System.String
    Private Partial Sub OnIDChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property LNAME() As Global.System.String
        Get
            Return _LNAME
        End Get
        Set
            OnLNAMEChanging(value)
            ReportPropertyChanging("LNAME")
            _LNAME = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("LNAME")
            OnLNAMEChanged()
        End Set
    End Property

    Private _LNAME As Global.System.String
    Private Partial Sub OnLNAMEChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnLNAMEChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property FNAME() As Global.System.String
        Get
            Return _FNAME
        End Get
        Set
            OnFNAMEChanging(value)
            ReportPropertyChanging("FNAME")
            _FNAME = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("FNAME")
            OnFNAMEChanged()
        End Set
    End Property

    Private _FNAME As Global.System.String
    Private Partial Sub OnFNAMEChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnFNAMEChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property MAJOR() As Global.System.String
        Get
            Return _MAJOR
        End Get
        Set
            OnMAJORChanging(value)
            ReportPropertyChanging("MAJOR")
            _MAJOR = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("MAJOR")
            OnMAJORChanged()
        End Set
    End Property

    Private _MAJOR As Global.System.String
    Private Partial Sub OnMAJORChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnMAJORChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property MINOR() As Global.System.String
        Get
            Return _MINOR
        End Get
        Set
            OnMINORChanging(value)
            ReportPropertyChanging("MINOR")
            _MINOR = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("MINOR")
            OnMINORChanged()
        End Set
    End Property

    Private _MINOR As Global.System.String
    Private Partial Sub OnMINORChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnMINORChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property ADVISOR() As Global.System.String
        Get
            Return _ADVISOR
        End Get
        Set
            OnADVISORChanging(value)
            ReportPropertyChanging("ADVISOR")
            _ADVISOR = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("ADVISOR")
            OnADVISORChanged()
        End Set
    End Property

    Private _ADVISOR As Global.System.String
    Private Partial Sub OnADVISORChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnADVISORChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property GPA1() As Global.System.String
        Get
            Return _GPA1
        End Get
        Set
            OnGPA1Changing(value)
            ReportPropertyChanging("GPA1")
            _GPA1 = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("GPA1")
            OnGPA1Changed()
        End Set
    End Property

    Private _GPA1 As Global.System.String
    Private Partial Sub OnGPA1Changing(value As Global.System.String)
    End Sub

    Private Partial Sub OnGPA1Changed()
    End Sub

    #End Region
    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("Student", "StudentSemester", "Semester")>
     Public Property Semesters() As EntityCollection(Of Semester)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Semester)("Student.StudentSemester", "Semester")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Semester)("Student.StudentSemester", "Semester", value)
            End If
        End Set
    End Property

    #End Region
End Class

#End Region

