SUBROUTINE GET_ITEMS_OUT(RUNNING_TOTAL, MEMBER_ID) 
* 9/24/10 - v1.00 - Used in MEMBERS File
* 6/7/11 - v1.01 - Need to fix RENTAL_DETAILS references

OPEN "","RENTAL_DETAILS" TO RENTAL_DETAILS ELSE STOP
RUNNING_TOTAL = 0
EXECUTE "SELECT RENTAL_DETAILS WITH CUSTOMER_CODE =":MEMBER_ID CAPTURING OUTPUT
LOOP
    READNEXT ID ELSE EXIT
        READ ITEM FROM RENTAL_DETAILS, ID ELSE CONTINUE
        LIM = DCOUNT(ITEM<7>,@VM)
        FOR I=1 TO LIM
            IF ITEM<9,I> = '' THEN
                RUNNING_TOTAL += 1
            END
        NEXT I  
REPEAT

RETURN
