//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

//[assembly: EdmSchemaAttribute()]

namespace U2_oData_WebApplication
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class XDEMOEntities1 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new XDEMOEntities1 object using the connection string found in the 'XDEMOEntities1' section of the application configuration file.
        /// </summary>
        public XDEMOEntities1() : base("name=XDEMOEntities1", "XDEMOEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new XDEMOEntities1 object.
        /// </summary>
        public XDEMOEntities1(string connectionString) : base(connectionString, "XDEMOEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new XDEMOEntities1 object.
        /// </summary>
        public XDEMOEntities1(EntityConnection connection) : base(connection, "XDEMOEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PRODUCT3> PRODUCT3S
        {
            get
            {
                if ((_PRODUCT3S == null))
                {
                    _PRODUCT3S = base.CreateObjectSet<PRODUCT3>("PRODUCT3S");
                }
                return _PRODUCT3S;
            }
        }
        private ObjectSet<PRODUCT3> _PRODUCT3S;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PRODUCT3S EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPRODUCT3S(PRODUCT3 pRODUCT3)
        {
            base.AddObject("PRODUCT3S", pRODUCT3);
        }

        #endregion
        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<PRODUCT3> f_XDEMO_GETPRODUCTS()
        {
            return base.ExecuteFunction<PRODUCT3>("f_XDEMO_GETPRODUCTS");
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="mergeOption"></param>
        public ObjectResult<PRODUCT3> f_XDEMO_GETPRODUCTS(MergeOption mergeOption)
        {
            return base.ExecuteFunction<PRODUCT3>("f_XDEMO_GETPRODUCTS", mergeOption);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="XDEMOModel1", Name="PRODUCT3")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PRODUCT3 : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PRODUCT3 object.
        /// </summary>
        /// <param name="pRODUCT_ID">Initial value of the PRODUCT_ID property.</param>
        public static PRODUCT3 CreatePRODUCT3(global::System.Decimal pRODUCT_ID)
        {
            PRODUCT3 pRODUCT3 = new PRODUCT3();
            pRODUCT3.PRODUCT_ID = pRODUCT_ID;
            return pRODUCT3;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal PRODUCT_ID
        {
            get
            {
                return _PRODUCT_ID;
            }
            set
            {
                if (_PRODUCT_ID != value)
                {
                    OnPRODUCT_IDChanging(value);
                    ReportPropertyChanging("PRODUCT_ID");
                    _PRODUCT_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PRODUCT_ID");
                    OnPRODUCT_IDChanged();
                }
            }
        }
        private global::System.Decimal _PRODUCT_ID;
        partial void OnPRODUCT_IDChanging(global::System.Decimal value);
        partial void OnPRODUCT_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TITLE
        {
            get
            {
                return _TITLE;
            }
            set
            {
                OnTITLEChanging(value);
                ReportPropertyChanging("TITLE");
                _TITLE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TITLE");
                OnTITLEChanged();
            }
        }
        private global::System.String _TITLE;
        partial void OnTITLEChanging(global::System.String value);
        partial void OnTITLEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RATING
        {
            get
            {
                return _RATING;
            }
            set
            {
                OnRATINGChanging(value);
                ReportPropertyChanging("RATING");
                _RATING = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RATING");
                OnRATINGChanged();
            }
        }
        private global::System.String _RATING;
        partial void OnRATINGChanging(global::System.String value);
        partial void OnRATINGChanged();

        #endregion
    
    }

    #endregion
    
}
