'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Course
    Public Property ID As String
    Public Property CGA_MV_KEY As Integer
    Public Property CGA_MS_KEY As Integer
    Public Property COURSE_NBR As String
    Public Property COURSE_HOURS As String
    Public Property COURSE_NAME As String
    Public Property TEACHER As String
    Public Property COURSE_GRD As String

    Public Overridable Property Semester As Semester

End Class
