'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CUSTOMER_MV
    Public Property CUSTID As Integer
    Public Property FNAME As String
    Public Property LNAME As String
    Public Property SVC_PAID_DATE As Nullable(Of Date)
    Public Property SVC_PRICE As Nullable(Of Integer)
    Public Property SVC_END As Nullable(Of Date)
    Public Property SVC_START As Nullable(Of Date)
    Public Property DISCOUNT As Nullable(Of Decimal)
    Public Property PRICE As Nullable(Of Integer)
    Public Property LIST_PRICE As Nullable(Of Integer)
    Public Property PAID_DATE As Nullable(Of Date)
    Public Property BUY_DATE As Nullable(Of Date)
    Public Property SER_NUM As String
    Public Property DESCRIPTION As String
    Public Property PRODID As String

End Class
