'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CUSTOMER
    Public Property CUSTID As Integer
    Public Property PHONE As String
    Public Property ZIP As String
    Public Property STATENAME As String
    Public Property STATE As String
    Public Property CITY As String
    Public Property FULLADDR As String
    Public Property ADDR2 As String
    Public Property ADDR1 As String
    Public Property COMPANY As String
    Public Property FULLNAME As String
    Public Property LNAME As String
    Public Property FNAME As String
    Public Property SAL As String

End Class
