//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("Student", "StudentSemester", "Student", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(EntityFramework_Subroutine.Student), "Semester", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EntityFramework_Subroutine.Semester), true)]
[assembly: EdmRelationshipAttribute("Student", "SemesterCourse", "Semester", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(EntityFramework_Subroutine.Semester), "Course", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EntityFramework_Subroutine.Course), true)]

#endregion

namespace EntityFramework_Subroutine
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class StudentContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new StudentContainer object using the connection string found in the 'StudentContainer' section of the application configuration file.
        /// </summary>
        public StudentContainer() : base("name=StudentContainer", "StudentContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new StudentContainer object.
        /// </summary>
        public StudentContainer(string connectionString) : base(connectionString, "StudentContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new StudentContainer object.
        /// </summary>
        public StudentContainer(EntityConnection connection) : base(connection, "StudentContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Student> Students
        {
            get
            {
                if ((_Students == null))
                {
                    _Students = base.CreateObjectSet<Student>("Students");
                }
                return _Students;
            }
        }
        private ObjectSet<Student> _Students;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Semester> Semesters
        {
            get
            {
                if ((_Semesters == null))
                {
                    _Semesters = base.CreateObjectSet<Semester>("Semesters");
                }
                return _Semesters;
            }
        }
        private ObjectSet<Semester> _Semesters;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Course> Courses
        {
            get
            {
                if ((_Courses == null))
                {
                    _Courses = base.CreateObjectSet<Course>("Courses");
                }
                return _Courses;
            }
        }
        private ObjectSet<Course> _Courses;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Students EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToStudents(Student student)
        {
            base.AddObject("Students", student);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Semesters EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSemesters(Semester semester)
        {
            base.AddObject("Semesters", semester);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Courses EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCourses(Course course)
        {
            base.AddObject("Courses", course);
        }

        #endregion
        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="cMD">No Metadata Documentation available.</param>
        /// <param name="oPTIONS">No Metadata Documentation available.</param>
        /// <param name="rESULT">No Metadata Documentation available.</param>
        /// <param name="xSD_DATA">No Metadata Documentation available.</param>
        /// <param name="eRRMSG">No Metadata Documentation available.</param>
        /// <param name="eRRNUM">No Metadata Documentation available.</param>
        public int GetXmlSubroutine(global::System.String cMD, global::System.String oPTIONS, ObjectParameter rESULT, ObjectParameter xSD_DATA, ObjectParameter eRRMSG, ObjectParameter eRRNUM)
        {
            ObjectParameter cMDParameter;
            if (cMD != null)
            {
                cMDParameter = new ObjectParameter("CMD", cMD);
            }
            else
            {
                cMDParameter = new ObjectParameter("CMD", typeof(global::System.String));
            }
    
            ObjectParameter oPTIONSParameter;
            if (oPTIONS != null)
            {
                oPTIONSParameter = new ObjectParameter("OPTIONS", oPTIONS);
            }
            else
            {
                oPTIONSParameter = new ObjectParameter("OPTIONS", typeof(global::System.String));
            }
    
            return base.ExecuteFunction("GetXmlSubroutine", cMDParameter, oPTIONSParameter, rESULT, xSD_DATA, eRRMSG, eRRNUM);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Student", Name="Course")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Course : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Course object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="cGA_MV_KEY">Initial value of the CGA_MV_KEY property.</param>
        /// <param name="cGA_MS_KEY">Initial value of the CGA_MS_KEY property.</param>
        public static Course CreateCourse(global::System.String id, global::System.Int32 cGA_MV_KEY, global::System.Int32 cGA_MS_KEY)
        {
            Course course = new Course();
            course.ID = id;
            course.CGA_MV_KEY = cGA_MV_KEY;
            course.CGA_MS_KEY = cGA_MS_KEY;
            return course;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.String _ID;
        partial void OnIDChanging(global::System.String value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CGA_MV_KEY
        {
            get
            {
                return _CGA_MV_KEY;
            }
            set
            {
                if (_CGA_MV_KEY != value)
                {
                    OnCGA_MV_KEYChanging(value);
                    ReportPropertyChanging("CGA_MV_KEY");
                    _CGA_MV_KEY = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CGA_MV_KEY");
                    OnCGA_MV_KEYChanged();
                }
            }
        }
        private global::System.Int32 _CGA_MV_KEY;
        partial void OnCGA_MV_KEYChanging(global::System.Int32 value);
        partial void OnCGA_MV_KEYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CGA_MS_KEY
        {
            get
            {
                return _CGA_MS_KEY;
            }
            set
            {
                if (_CGA_MS_KEY != value)
                {
                    OnCGA_MS_KEYChanging(value);
                    ReportPropertyChanging("CGA_MS_KEY");
                    _CGA_MS_KEY = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CGA_MS_KEY");
                    OnCGA_MS_KEYChanged();
                }
            }
        }
        private global::System.Int32 _CGA_MS_KEY;
        partial void OnCGA_MS_KEYChanging(global::System.Int32 value);
        partial void OnCGA_MS_KEYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String COURSE_NBR
        {
            get
            {
                return _COURSE_NBR;
            }
            set
            {
                OnCOURSE_NBRChanging(value);
                ReportPropertyChanging("COURSE_NBR");
                _COURSE_NBR = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("COURSE_NBR");
                OnCOURSE_NBRChanged();
            }
        }
        private global::System.String _COURSE_NBR;
        partial void OnCOURSE_NBRChanging(global::System.String value);
        partial void OnCOURSE_NBRChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String COURSE_HOURS
        {
            get
            {
                return _COURSE_HOURS;
            }
            set
            {
                OnCOURSE_HOURSChanging(value);
                ReportPropertyChanging("COURSE_HOURS");
                _COURSE_HOURS = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("COURSE_HOURS");
                OnCOURSE_HOURSChanged();
            }
        }
        private global::System.String _COURSE_HOURS;
        partial void OnCOURSE_HOURSChanging(global::System.String value);
        partial void OnCOURSE_HOURSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String COURSE_NAME
        {
            get
            {
                return _COURSE_NAME;
            }
            set
            {
                OnCOURSE_NAMEChanging(value);
                ReportPropertyChanging("COURSE_NAME");
                _COURSE_NAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("COURSE_NAME");
                OnCOURSE_NAMEChanged();
            }
        }
        private global::System.String _COURSE_NAME;
        partial void OnCOURSE_NAMEChanging(global::System.String value);
        partial void OnCOURSE_NAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TEACHER
        {
            get
            {
                return _TEACHER;
            }
            set
            {
                OnTEACHERChanging(value);
                ReportPropertyChanging("TEACHER");
                _TEACHER = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TEACHER");
                OnTEACHERChanged();
            }
        }
        private global::System.String _TEACHER;
        partial void OnTEACHERChanging(global::System.String value);
        partial void OnTEACHERChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String COURSE_GRD
        {
            get
            {
                return _COURSE_GRD;
            }
            set
            {
                OnCOURSE_GRDChanging(value);
                ReportPropertyChanging("COURSE_GRD");
                _COURSE_GRD = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("COURSE_GRD");
                OnCOURSE_GRDChanged();
            }
        }
        private global::System.String _COURSE_GRD;
        partial void OnCOURSE_GRDChanging(global::System.String value);
        partial void OnCOURSE_GRDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Student", "SemesterCourse", "Semester")]
        public Semester Semester
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Semester>("Student.SemesterCourse", "Semester").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Semester>("Student.SemesterCourse", "Semester").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Semester> SemesterReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Semester>("Student.SemesterCourse", "Semester");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Semester>("Student.SemesterCourse", "Semester", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Student", Name="Semester")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Semester : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Semester object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="cGA_MV_KEY">Initial value of the CGA_MV_KEY property.</param>
        public static Semester CreateSemester(global::System.String id, global::System.Int32 cGA_MV_KEY)
        {
            Semester semester = new Semester();
            semester.ID = id;
            semester.CGA_MV_KEY = cGA_MV_KEY;
            return semester;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.String _ID;
        partial void OnIDChanging(global::System.String value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CGA_MV_KEY
        {
            get
            {
                return _CGA_MV_KEY;
            }
            set
            {
                if (_CGA_MV_KEY != value)
                {
                    OnCGA_MV_KEYChanging(value);
                    ReportPropertyChanging("CGA_MV_KEY");
                    _CGA_MV_KEY = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CGA_MV_KEY");
                    OnCGA_MV_KEYChanged();
                }
            }
        }
        private global::System.Int32 _CGA_MV_KEY;
        partial void OnCGA_MV_KEYChanging(global::System.Int32 value);
        partial void OnCGA_MV_KEYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SEMESTER
        {
            get
            {
                return _SEMESTER;
            }
            set
            {
                OnSEMESTERChanging(value);
                ReportPropertyChanging("SEMESTER");
                _SEMESTER = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SEMESTER");
                OnSEMESTERChanged();
            }
        }
        private global::System.String _SEMESTER;
        partial void OnSEMESTERChanging(global::System.String value);
        partial void OnSEMESTERChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Student", "StudentSemester", "Student")]
        public Student Student
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Student>("Student.StudentSemester", "Student").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Student>("Student.StudentSemester", "Student").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Student> StudentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Student>("Student.StudentSemester", "Student");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Student>("Student.StudentSemester", "Student", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Student", "SemesterCourse", "Course")]
        public EntityCollection<Course> Courses
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Course>("Student.SemesterCourse", "Course");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Course>("Student.SemesterCourse", "Course", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Student", Name="Student")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Student : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Student object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static Student CreateStudent(global::System.String id)
        {
            Student student = new Student();
            student.ID = id;
            return student;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.String _ID;
        partial void OnIDChanging(global::System.String value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LNAME
        {
            get
            {
                return _LNAME;
            }
            set
            {
                OnLNAMEChanging(value);
                ReportPropertyChanging("LNAME");
                _LNAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LNAME");
                OnLNAMEChanged();
            }
        }
        private global::System.String _LNAME;
        partial void OnLNAMEChanging(global::System.String value);
        partial void OnLNAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FNAME
        {
            get
            {
                return _FNAME;
            }
            set
            {
                OnFNAMEChanging(value);
                ReportPropertyChanging("FNAME");
                _FNAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FNAME");
                OnFNAMEChanged();
            }
        }
        private global::System.String _FNAME;
        partial void OnFNAMEChanging(global::System.String value);
        partial void OnFNAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MAJOR
        {
            get
            {
                return _MAJOR;
            }
            set
            {
                OnMAJORChanging(value);
                ReportPropertyChanging("MAJOR");
                _MAJOR = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MAJOR");
                OnMAJORChanged();
            }
        }
        private global::System.String _MAJOR;
        partial void OnMAJORChanging(global::System.String value);
        partial void OnMAJORChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MINOR
        {
            get
            {
                return _MINOR;
            }
            set
            {
                OnMINORChanging(value);
                ReportPropertyChanging("MINOR");
                _MINOR = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MINOR");
                OnMINORChanged();
            }
        }
        private global::System.String _MINOR;
        partial void OnMINORChanging(global::System.String value);
        partial void OnMINORChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ADVISOR
        {
            get
            {
                return _ADVISOR;
            }
            set
            {
                OnADVISORChanging(value);
                ReportPropertyChanging("ADVISOR");
                _ADVISOR = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ADVISOR");
                OnADVISORChanged();
            }
        }
        private global::System.String _ADVISOR;
        partial void OnADVISORChanging(global::System.String value);
        partial void OnADVISORChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GPA1
        {
            get
            {
                return _GPA1;
            }
            set
            {
                OnGPA1Changing(value);
                ReportPropertyChanging("GPA1");
                _GPA1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GPA1");
                OnGPA1Changed();
            }
        }
        private global::System.String _GPA1;
        partial void OnGPA1Changing(global::System.String value);
        partial void OnGPA1Changed();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Student", "StudentSemester", "Semester")]
        public EntityCollection<Semester> Semesters
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Semester>("Student.StudentSemester", "Semester");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Semester>("Student.StudentSemester", "Semester", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
