//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework_POCO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Semester
    {
        public Semester()
        {
            this.Courses = new HashSet<Course>();
        }
    
        public string ID { get; set; }
        public int CGA_MV_KEY { get; set; }
        public string SEMESTER { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual ICollection<Course> Courses { get; set; }
    }
}
